DROP DATABASE IF EXISTS DBACADEMIA;
CREATE DATABASE DBACADEMIA;
USE DBACADEMIA;


CREATE TABLE ENDERECO(
ID INT NOT NULL AUTO_INCREMENT
, ESTADO CHAR(2)
, CIDADE VARCHAR(250)
, BAIRRO VARCHAR(250)
, RUA VARCHAR(250)
, NUMERO VARCHAR(5)
, COMPLEMENTO VARCHAR(10)
, CEP VARCHAR(8)
, PRIMARY KEY(ID)
);

CREATE TABLE PESSOA(
ID INT NOT NULL AUTO_INCREMENT
, ID_ENDERECO INT 
, CPF VARCHAR(11)
, NOME VARCHAR(250)
, TELEFONE VARCHAR(11)
, DT_NASCIMENTO DATE
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE TIPOUSUARIO (
ID INT NOT NULL AUTO_INCREMENT
, DESCRICAO VARCHAR(12)
, PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
ID INT NOT NULL AUTO_INCREMENT
, ID_PESSOA INT
, ID_TIPOUSUARIO INT
, MATRICULA INT
, EMAIL VARCHAR(100)
, LOGIN VARCHAR(10)
, SENHA VARCHAR(4)
, VALORHORA DOUBLE
, DT_CADASTRO DATETIME
, DT_EXPIRACAO DATETIME
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID)
, FOREIGN KEY (ID_TIPOUSUARIO) REFERENCES TIPOUSUARIO(ID)
);


CREATE TABLE TREINO(
ID INT NOT NULL AUTO_INCREMENT
, ID_CLIENTE INT
, ID_PROFISSIONAL INT
, TREINO TEXT
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID)
, FOREIGN KEY (ID_PROFISSIONAL) REFERENCES USUARIO(ID)
);


CREATE TABLE AGENDAMENTO(
ID INT NOT NULL AUTO_INCREMENT
, ID_CLIENTE INT
, ID_PROFISSIONAL INT 
, DATAHORA_INICIO DATETIME
, DATAHORA_FINAL DATETIME
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID)
, FOREIGN KEY (ID_PROFISSIONAL) REFERENCES USUARIO(ID)
);