DROP DATABASE IF EXISTS DBACADEMIA;
CREATE DATABASE DBACADEMIA;
USE DBACADEMIA;


CREATE TABLE ENDERECO(
ID INT NOT NULL AUTO_INCREMENT
, RUA VARCHAR(350)
, NUMERO VARCHAR(12)
, CEP VARCHAR(12)
, COMPLEMENTO VARCHAR(250)
, BAIRRO VARCHAR(250)
, CIDADE VARCHAR(250)
, ESTADO VARCHAR(2)
, PRIMARY KEY(ID)
);

CREATE TABLE PESSOA(
ID INT NOT NULL AUTO_INCREMENT
, ID_ENDERECO INT
, NOME VARCHAR(350)
, CPF VARCHAR(12)
, TELEFONE VARCHAR(12)
, DT_NASCIMENTO VARCHAR(12)
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE TIPOUSUARIO (
ID INT NOT NULL AUTO_INCREMENT
, DESCRICAO VARCHAR(30)
, PRIMARY KEY(ID)
);

CREATE TABLE NIVEL_TREINO(
ID INT NOT NULL AUTO_INCREMENT
, DESCRICAO VARCHAR(30)
, PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
ID INT NOT NULL AUTO_INCREMENT
, ID_PESSOA INT
, ID_TIPOUSUARIO INT
, MATRICULA INT
, VALORHORA DOUBLE
, EMAIL VARCHAR(350)
, LOGIN VARCHAR(350)
, SENHA VARCHAR(4)
, DT_CADASTRO DATETIME
, DT_EXPIRACAO DATETIME
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID)
, FOREIGN KEY (ID_TIPOUSUARIO) REFERENCES TIPOUSUARIO(ID)
);


CREATE TABLE TREINO(
ID INT NOT NULL AUTO_INCREMENT
, ID_CLIENTE INT
, ID_PROFISSIONAL INT
, ID_NIVEL_TREINO INT 
, DT_CADASTRO DATETIME
, DT_TERMINO DATETIME
, TREINO TEXT
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID)
, FOREIGN KEY (ID_PROFISSIONAL) REFERENCES USUARIO(ID)
, FOREIGN KEY (ID_NIVEL_TREINO) REFERENCES NIVEL_TREINO(ID)
);


CREATE TABLE AGENDAMENTO(
ID INT NOT NULL AUTO_INCREMENT
, ID_CLIENTE INT
, ID_PROFISSIONAL INT 
, ACEITO BOOLEAN
, MOTIVO_REJEICAO VARCHAR(250)
, DATAHORA_INICIO DATETIME
, DATAHORA_FINAL DATETIME
, PRIMARY KEY(ID)
, FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID)
, FOREIGN KEY (ID_PROFISSIONAL) REFERENCES USUARIO(ID)
);