USE DBACADEMIA;

INSERT INTO TIPOUSUARIO (DESCRICAO) 
VALUES 
	('ADMINISTRADOR')
	, ('PERSONAL')
	, ('CLIENTE');
    
INSERT INTO NIVELTREINO (DESCRICAO) 
VALUES 
	('BASICO')
	, ('INTERMEDIARIO')
	, ('AVANCADO');
    

