USE DBACADEMIA;

INSERT INTO TIPOUSUARIO (DESCRICAO) 
VALUES 
	('ADMINISTRADOR')
	, ('PERSONAL')
	, ('CLIENTE');
    
INSERT INTO NIVELTREINO (DESCRICAO) 
VALUES 
	('BASICO')
	, ('INTERMEDIARIO')
	, ('AVANCADO');
	
INSERT INTO ENDERECO(RUA , NUMERO , CEP , COMPLEMENTO, BAIRRO , CIDADE, ESTADO)
VALUES ('Rua Bertoldo Simas', '12', '888888','APTO 09', 'Universitario', 'Florianopolis', 'SC');

INSERT INTO PESSOA (ID_ENDERECO, NOME , CPF, TELEFONE, DT_NASCIMENTO) 
VALUES (1, 'Renan Duarte Leal', '09410571232', '48999887221', CURDATE());

INSERT INTO USUARIO (ID_PESSOA, ID_TIPOUSUARIO, MATRICULA, VALORHORA , EMAIL , LOGIN , SENHA , DT_CADASTRO , DT_EXPIRACAO)
VALUES (1, 1, '4455', NULL, 'renan.leal@yahoo.com', 'renan.leal', '1705', now(), NULL)